import { Geist, Geist_Mono, Sora } from "next/font/google";
import "./globals.css";

// Оригинальные шрифты
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ➕ Добавляем Sora
const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ['100','200','300','400','500','600','700','800'],
});

export const metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sora.variable} antialiased overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
